// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int64              `json:"id"`
	Owner     string             `json:"owner"`
	Balance   int64              `json:"balance"`
	Currency  string             `json:"currency"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Entry struct {
	ID        int64              `json:"id"`
	AccountID int64              `json:"account_id"`
	Amount    int64              `json:"amount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Transfer struct {
	ID            int64              `json:"id"`
	FromAccountID int64              `json:"from_account_id"`
	ToAccountID   int64              `json:"to_account_id"`
	Amount        int64              `json:"amount"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	Name               string             `json:"name"`
	HashedPassword     string             `json:"hashed_password"`
	FullName           string             `json:"full_name"`
	Email              string             `json:"email"`
	PasswordLastChange pgtype.Timestamptz `json:"password_last_change"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}
